# Python for AI QuickStart

Code authored by: Shaw Talebi

YouTube video: https://youtu.be/pNg2DJ4spXg <br>
Blog post: https://medium.com/towards-data-science/python-quickstart-for-people-learning-ai-58a1b76df0f4

## Data Types

#### Strings & Numbers

In [1]:
"this is a string"

'this is a string'

In [2]:
'so is this:-1*!@&04"(*&^}":>?'

'so is this:-1*!@&04"(*&^}":>?'

In [3]:
"""and
    this is
        too!!11!"""

'and\n    this is\n        too!!11!'

In [4]:
"we can even " + "add strings together"

'we can even add strings together'

In [6]:
# we can't add strings to other data types (BTW this is how you write comments in Python)
"I am " + 29

TypeError: can only concatenate str (not "int") to str

In [7]:
# so we have to write 29 as a string
"I am " + "29"

'I am 29'

#### Lists & Dictionaries

In [8]:
# a list of strings
["a", "b", "c"]

['a', 'b', 'c']

In [9]:
# a list of ints
[1, 2, 3]

[1, 2, 3]

In [10]:
# list with a string, int, and float
["a", 2, 3.14]

['a', 2, 3.14]

In [11]:
# a list of lists with mixed types
[["a", "b"], [1, 2], [1.0, 2.0]]

[['a', 'b'], [1, 2], [1.0, 2.0]]

In [12]:
# a dictionary
{"Name":"Shaw"}

{'Name': 'Shaw'}

In [13]:
# a dictionary with multiple key-value pairs
{"Name":"Shaw", "Age":29, "Interests":["AI", "Music", "Bread"]}

{'Name': 'Shaw', 'Age': 29, 'Interests': ['AI', 'Music', 'Bread']}

In [14]:
# a list of dictionaries
[{"Name":"Shaw", "Age":29, "Interests":["AI", "Music", "Bread"]}, {"Name":"Ify", "Age":27, "Interests":["Marketing", "YouTube", "Shopping"]}]

[{'Name': 'Shaw', 'Age': 29, 'Interests': ['AI', 'Music', 'Bread']},
 {'Name': 'Ify', 'Age': 27, 'Interests': ['Marketing', 'YouTube', 'Shopping']}]

In [15]:
# a nested dictionary
{"User":{"Name":"Shaw", "Age":29, "Interests":["AI", "Music", "Bread"]}, "Last_login":"2024-09-06", "Membership_Tier":"Free"}

{'User': {'Name': 'Shaw', 'Age': 29, 'Interests': ['AI', 'Music', 'Bread']},
 'Last_login': '2024-09-06',
 'Membership_Tier': 'Free'}

## Variables

In [16]:
# creating a variable and printing it
user_name = "Shaw"
print(user_name)

Shaw


In [17]:
# defining more variables and printing them as a formatted string. Notice, this automatically converts each variable to a string before printing!
user_age = 29
user_interests = ["AI", "Music", "Bread"]

print(f"{user_name} is {user_age} years old. His interests include {user_interests}.")

Shaw is 29 years old. His interests include ['AI', 'Music', 'Bread'].


In [18]:
# storing variables in a dictionary and printing them as a formatted string 
user_dict = {"Name":user_name, "Age":user_age, "Interests":user_interests}

print(f'{user_dict["Name"]} is {user_dict["Age"]} years old. His interests include {user_dict["Interests"]}.')

Shaw is 29 years old. His interests include ['AI', 'Music', 'Bread'].


In [19]:
# or we can print just one interest
f'{user_dict["Name"]} is {user_dict["Age"]} years old and is interested in {user_dict["Interests"][0]}.'

'Shaw is 29 years old and is interested in AI.'

## Loops & Conditionals

#### for loop

In [20]:
# a simple for loop iterating over a sequence of numbers
for i in range(5):
    # print ith element
    print(i)

0
1
2
3
4


In [21]:
# for loop iterating over a list
user_interests = ["AI", "Music", "Bread"]

for interest in user_interests:
    # print each item in list
    print(interest)

AI
Music
Bread


In [22]:
# for loop iterating over items in a dictionary
user_dict = {"Name":"Shaw", "Age":29, "Interests":["AI", "Music", "Bread"]}

for key, value in user_dict.items():
    # print each key and corresponding value
    print(key, "=", value)

Name = Shaw
Age = 29
Interests = ['AI', 'Music', 'Bread']


#### if-else

In [23]:
# check if user is 18 or older
if user_dict["Age"] >= 18:
    print("User is an adult")

User is an adult


In [24]:
# check if user is 1000 or older, if not print they have much to learn
if user_dict["Age"] >= 1000:
    print("User is wise")
else:
    print("User has much to learn")

User has much to learn


In [25]:
# count the number of users interested in bread
user_list = [{"Name":"Shaw", "Age":29, "Interests":["AI", "Music", "Bread"]}, {"Name":"Ify", "Age":27, "Interests":["Marketing", "YouTube", "Shopping"]}]
count = 0

for user in user_list:
    if "Bread" in user["Interests"]:
        count = count + 1

print(count, "user(s) interested in Bread")

1 user(s) interested in Bread


In [26]:
# count the number of users interested in an arbritrary topic
count = 0
topic = "Antiquing"

for user in user_list:
    if topic in user["Interests"]:
        count = count + 1

print(f"{count} user(s) interested in {topic}")

0 user(s) interested in Antiquing


## Functions

#### basic functions

In [27]:
# print(), a function we've used several times already

for key in user_dict.keys():
    print(key, ":", user_dict[key])

Name : Shaw
Age : 29
Interests : ['AI', 'Music', 'Bread']


In [28]:
# type(), getting the data type of a variable

for key in user_dict.keys():
    print(key, ":", type(user_dict[key]))

Name : <class 'str'>
Age : <class 'int'>
Interests : <class 'list'>


In [29]:
# len(), getting the length of a variable

for key in user_dict.keys():
    print(key, ":", len(user_dict[key]))

Name : 4


TypeError: object of type 'int' has no len()

In [30]:
# since len() is not defined for ints we can skip it

for key in user_dict.keys():
    # skips ints
    if type(user_dict[key]) is int:
        continue
    
    print(key, "length :", len(user_dict[key]))

Name length : 4
Interests length : 3


#### string methods

In [31]:
# make string all lowercase
print(user_dict["Name"].lower())

shaw


In [32]:
# make string all uppercase
print(user_dict["Name"].upper())

SHAW


In [33]:
# split string into list based on a specific character sequence
print(user_dict["Name"].split("ha"))

['S', 'w']


In [34]:
# replace a character sequence with another
print(user_dict["Name"].replace("w", "whin"))

Shawhin


#### list methods

In [35]:
# add an element to the end of a list
user_dict["Interests"].append("Entrepreneurship")
print(user_dict["Interests"])

['AI', 'Music', 'Bread', 'Entrepreneurship']


In [36]:
# remove a specific element from a list
user_dict["Interests"].pop(0)
print(user_dict["Interests"])

['Music', 'Bread', 'Entrepreneurship']


In [37]:
# insert an element into a specific place in a list
user_dict["Interests"].insert(1, "AI")
print(user_dict["Interests"])

['Music', 'AI', 'Bread', 'Entrepreneurship']


#### dict methods

In [38]:
# accessing dict keys
print(user_dict.keys())

dict_keys(['Name', 'Age', 'Interests'])


In [39]:
# accessing dict values
print(user_dict.values())

dict_values(['Shaw', 29, ['Music', 'AI', 'Bread', 'Entrepreneurship']])


In [40]:
# accessing dict items
print(user_dict.items())

dict_items([('Name', 'Shaw'), ('Age', 29), ('Interests', ['Music', 'AI', 'Bread', 'Entrepreneurship'])])


In [41]:
# removing a key
user_dict.pop("Name")
print(user_dict.items())

dict_items([('Age', 29), ('Interests', ['Music', 'AI', 'Bread', 'Entrepreneurship'])])


In [42]:
# adding a key
user_dict["Name"] = "Shaw"
print(user_dict.items())

dict_items([('Age', 29), ('Interests', ['Music', 'AI', 'Bread', 'Entrepreneurship']), ('Name', 'Shaw')])


#### user-defined functions

In [43]:
def user_description(user_dict):
    """
        Function to return a sentence (string) describing input user
    """
    return f'{user_dict["Name"]} is {user_dict["Age"]} years old and is interested in {user_dict["Interests"][0]}.'

In [44]:
# print user description
description = user_description(user_dict)
print(description)

# print description for a new user!
new_user_dict = {"Name":"Ify", "Age":27, "Interests":["Marketing", "YouTube", "Shopping"]}
print(user_description(new_user_dict))

Shaw is 29 years old and is interested in Music.
Ify is 27 years old and is interested in Marketing.


In [45]:
def interested_user_count(user_list, topic):
    """
        Function to count number of users interested in an arbitrary topic
    """
    count = 0

    for user in user_list:
        if topic in user["Interests"]:
            count = count + 1
    
    return count

In [46]:
# define user list and topic
user_list = [user_dict, new_user_dict]
topic = "Shopping"

# compute interested user count and print it
count = interested_user_count(user_list, topic)
print(f"{count} user(s) interested in {topic}")

1 user(s) interested in Shopping


## Libraries

In [47]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [48]:
# create a "vector"
v = np.array([1, 3, 6])
print(v)

[1 3 6]


In [49]:
# multiply a "vector"
print(2*v)

[ 2  6 12]


In [50]:
# create a matrix
X = np.array([v, 2*v, v/2])
print(X)

[[ 1.   3.   6. ]
 [ 2.   6.  12. ]
 [ 0.5  1.5  3. ]]


In [51]:
# matrix multiplication
print(np.matmul(X,v))

[46. 92. 23.]


In [52]:
# create a 1D array with 3 equally spaced values between 1 and 9
z = np.linspace(1, 9, 3)
print(z)

[1. 5. 9.]


In [53]:
# adding and substracting arrays
print(v + z)
print(v - z)

[ 2.  8. 15.]
[ 0. -2. -3.]


In [54]:
# reshaping arrays
print(X.reshape((9,)))
print(X.flatten())

[ 1.   3.   6.   2.   6.  12.   0.5  1.5  3. ]
[ 1.   3.   6.   2.   6.  12.   0.5  1.5  3. ]


In [55]:
# dot product
print(np.dot(v, z))
# cross product
print(np.cross(v, z))

70.0
[-3. -3.  2.]


In [56]:
# mean
print(np.mean(v))
# min
print(np.min(v))
# max
print(np.max(v))

3.3333333333333335
1
6


In [57]:
# array of random numbers between 0 and 1
print(np.random.rand(2,2))
# array of random ints between 0 and 10
print(np.random.randint(0, 10, size=5))

[[0.20457559 0.30824533]
 [0.53826289 0.49716523]]
[0 9 2 0 4]
